var
  fs     = require('fs'),
  path   = require('path'),
  expect = require('chai').expect,
  Report = require('../../index');

var options = {
  source: path.join(__dirname, './testdata/cucumber_report.json')
};

module.exports = function() {

  this.Given(/^a JSON file generated by cucumber$/, function (callback) {
    var json = JSON.parse(fs.readFileSync(options.source, 'UTF-8'));
    expect(json.length).to.equal(1); // Number of features
    callback();
  });

  this.Given(/^the destination directory is set to "([^"]*)"$/, function (arg1, callback) {
    options.dest = './' + arg1;
    callback();
  });

  this.Given(/^no template is provided$/, function (callback) {
    expect(options).to.not.have.property('template');
    callback();
  });

  this.Given(/^a custom template is provided$/, function (callback) {
    options.template = './templates/template2.html';
    expect(options).to.have.property('template');
    callback();
  });

  this.When(/^I run the report generator$/, function (callback) {
    new Report(options).createReport();
    callback();
  });

  this.Then(/^I should get a HTML report in the "([^"]*)" directory$/, function (arg1, callback) {
    var p = path.join('./' + arg1, 'index.html');
    expect(fs.existsSync(p)).to.equal(true);
    callback();
  });

};