Feature: Report Generator
  As a cucumber user
  I want to generate HTML reports from cucumber JSON report files
  So that I can get a better overview of my specifications

  Scenario: Generate report using default template
    Given a JSON file generated by cucumber
    And the destination directory is set to "reports"
    And no template is provided
    When I run the report generator
    Then I should get a HTML report in the "reports" directory

  Scenario: Generate report using custom template
    Given a JSON file generated by cucumber
    And the destination directory is set to "reports"
    And a custom template is provided
    When I run the report generator
    Then I should get a HTML report in the "reports" directory

  Scenario: Verify source JSON exists
    Given no JSON file is provided
    When I run the report generator
    Then I should get an error message

  Scenario: Verify template exists
    Given a JSON file generated by cucumber
    And an invalid template is provided
    When I run the report generator
    Then I should get an error message